#GET
http://localhost:8080/fish

###

#GET
http://localhost:8080/users


###
#GET
http://localhost:8080/calculate
Content-Type: application/json

{
    "dob": "2009-05-05"
}

###
#GET 
http://localhost:8080/calculate
Authorization: Beaer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJGZW5nc2h1aS5jb20iLCJzdWIiOiJzdHJpbmdAZ21haWwuY29tIiwiZXhwIjoxNzI4NDEzMjMzLCJpYXQiOjE3Mjg0MDYwMzMsInNjb3BlIjoiQWRtaW4ifQ.keHT2Y8lCgrwNhG3Bgkq4ai5aJosAVNm88U0Cmk7vAspyrds8rNL_teeAsGP7kIUa0tFLGNDzmEL4kVSYV5vTgW45GR0em2Gu7mGobEj4RTY7I2mi6vQX9-Rov5S1v-Dg
Content-Type: application/json
{
    "dob": "2009-05-05"
}
