
server:
  port: 8080


springdoc:
  api-docs:
    enabled: true
    path: /koifish-docs/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html  # ???ng d?n cho Swagger UI
    enabled: true

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/FengShuiKoiDB9"
    username: root
    password: 123456

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true

outbound:
  client-id: "311482209289-pgh12mi0hos00orqsl2773ke1gdsdhjf.apps.googleusercontent.com"
  client-secret: "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"
  redirect-uri: "http://localhost:3000/authenticate"

jwt:
  singerKey: "cq9cu5H3J3h1qWLxonaN4CFQy2J47Mnf/0vRPGek0SBZm//1k0V0CKAYlcC/G68A"



