server:
  port: 8080
  servlet:
    context-path: /FengShuiKoi

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/FengShuiKoiDB3"
    username: root
    password: 123456
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true




