
server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
    path: /koifish-docs/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html  # ???ng d?n cho Swagger UI
    enabled: true

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/FengShuiKoiDB9"
    username: root
    password: 123456

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true

jwt:
  singerKey: "cq9cu5H3J3h1qWLxonaN4CFQy2J47Mnf/0vRPGek0SBZm//1k0V0CKAYlcC/G68A"



