
server:
  port: 8080


springdoc:
  api-docs:
    enabled: true
    path: /koifish-docs/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html  # Path for Swagger UI
    enabled: true

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/FengShuiKoiDB8"
    username: root
    password: root

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true

  ai:
    openai:
      api-key: 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
      chat:
        options:
          model: gpt-3.5-turbo-0125

outbound:
  client-id: "311482209289-pgh12mi0hos00orqsl2773ke1gdsdhjf.apps.googleusercontent.com"
  client-secret: "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"
  redirect-uri: "http://localhost:3000/authenticate"

jwt:
  singerKey: "cq9cu5H3J3h1qWLxonaN4CFQy2J47Mnf/0vRPGek0SBZm//1k0V0CKAYlcC/G68A"



