server:
  port: 8088
  servlet:
    context-path: /feng-shui-koi
spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/feng-shui-koi"
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true