
server:
  port: 8080
  servlet:
    session:
      timeout: 5m

springdoc:
  api-docs:
    enabled: true
    path: /koifish-docs/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}

  application:
    name: sendemail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true

frontend:
  url: ${FRONTEND_URL}

outbound:
  client-id: ${OUTBOUND_CLIENT_ID}
  client-secret: ${OUTBOUND_CLIENT_SECRET}
  redirect-uri: ${OUTBOUND_REDIRECT_URI}

frontend:
  url: ${FRONTEND_URL}

jwt:
  singerKey: ${JWT_SIGNER_KEY}

api:
  stripe:
    key: ${API_STRIPE_KEY}

chat-gpt:
  key: ${CHAT_GPT_KEY}



